### PR TITLE
Add version of Pump() with status callbacks

### PR DESCRIPTION
**Pull request by KyleMaas**
This adds a version of the `Pump()` function which takes callback functions so the caller knows where we're at in the processing cycle.

This came up while seeking a solution for [https://github.com/ssbc/go-ssb/issues/251](https://github.com/ssbc/go-ssb/issues/251).  Since the Luigi `Pump()`s were all being run in goroutines, we had no way to know if the indexes had caught up with the main log to know whether or not they're in sync, which caused all kinds of problems.  This gives us a very easy way to fix that.

### CODE REVIEW

**Review by cryptix — COMMENTED** [review]
I like this, the only thing i'm not sure about anymore if the PushSource interface upgrade is used in go-ssb. I know we added it for some reason but... 🙈 

In either case I'd probably remove it from this new function since it sidesteps the callbacks.

**Comment by KyleMaas** [comment]
@cryptix Thanks for the feedback!  Not sure I can answer that question - I just copied it from the other version, so if it needs to be removed, it probably needs to be removed from both.

**Comment by cryptix** [comment]
I don't have the time to do a full scan for this but a cursory look just turned up two, probably also outdated, utilities in go-ssb that actually use PushSource. So it might be fine to reduce. I would have expected margaret or go-ssb's indexes to use this at least. Or it could have been for muxrpc, which used luigi before I ditched it there.

context: Not sure how familiar you are with Go's stdlib interfaces but Pump is akin to [io.Copy ](https://cs.opensource.google/go/go/+/refs/tags/go1.19.5:src/io/io.go;l=406-414;drc=2e792a8295d7c7f082cf2e3b163a3d4d30b6df7e)and PushSource was intended as something like WriteTo. Back then we were way to ignorant about the use of `interface{}` and the overhead it introduces on the runtime and the developers... Sadly i never got around to re-write margaret without using luigi. I started an experiment for this over [here](https://git.sr.ht/~cryptix/go-exp/tree/riese/item/holzriese). ((holz)riese is the german word for flume)

**Comment by KyleMaas** [comment]
So are we good to merge this, then, and try and tackle removing PushSource in a subsequent pull request against both projects?

**Comment by decentral1se** [comment]
PushSource follow ups are https://github.com/ssbc/go-luigi/issues/5 / https://github.com/ssbc/go-ssb/issues/304

**Comment by KyleMaas** [comment]
Awesome.  Thanks!

**Pull request merged**
